### ISSUE TITLE
fail on copying and plugin of zip

### ISSUE THREAD

**Issue by labba** [carlosgprado/NaFl#8]
windows 7 x64
download all with PIP as required and done the PIN as needed and done the config file but when executing the core:

C:\Python27\lib\site-packages\sqlalchemy\sql\base.py:291: SAWarning: Can't validate argument 'drizzle_engine'; can't locate any SQLAlchemy dialect nam
ed 'drizzle'
  (k, dialect_name))
=== [_] Registering node on the server...
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X Node registered successfully :)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
=== [_] Restoring saved bitmap from saved_bitmap.p...

=== Initializing Cthulhu... ===
=== THE BRINGER OF DEATH... ===

=== Initializing plugins... ===
=== Loading plugin example...
=== Loading plugin unzip...
=== [*] Copying all files from C:\Work\Tools\NaFl\NaFlCore\samples to C:\Work\Tools\NaFl\NaFlCore\mutations

> Preprocessing input...
> Traceback (most recent call last):
>   File "C:\Work\Tools\NaFl\NaFlCore\NaFlCore.py", line 267, in <module>
>     main()
>   File "C:\Work\Tools\NaFl\NaFlCore\NaFlCore.py", line 249, in main
>     fuzzing_loop()  # never returns
>   File "C:\Work\Tools\NaFl\NaFlCore\NaFlCore.py", line 173, in fuzzing_loop
>     mutation_filename = filegen.write_test_case()
>   File "C:\Work\Tools\NaFl\NaFlCore\helpers\mutator.py", line 77, in write_test_case
>     mutated_contents = self._gen_mutation()
>   File "C:\Work\Tools\NaFl\NaFlCore\helpers\mutator.py", line 68, in _gen_mutation
>     m = self.cthulhu.yield_mutation(original_contents)
>   File "C:\Work\Tools\NaFl\NaFlCore\helpers\mutator.py", line 186, in yield_mutation
>     buf = self.apply_pre_processing(file_contents)
>   File "C:\Work\Tools\NaFl\NaFlCore\helpers\mutator.py", line 150, in apply_pre_processing
>     data, self.data_to_post = plugin.pre(data)
>   File "./plugins\unzip__init__.py", line 36, in pre
>     zin = zipfile.ZipFile(file_like_object, mode = 'r')
>   File "C:\Python27\lib\zipfile.py", line 793, in **init**
>     self._RealGetContents()
>   File "C:\Python27\lib\zipfile.py", line 835, in _RealGetContents
>     raise BadZipfile, "File is not a zip file"
> zipfile.BadZipfile: File is not a zip file

**Comment by carlosgprado** [comment]
The problem was all plugins were being applied without ability to select which ones we wanted.
See the section plugins in the config.ini file.
Plugin name in the config is the same as the directory under `plugins`. 
Plugin names not in config file are disabled by default.

Example:

```
[plugins]
; NOTE: specify the plugins in the order you want them applied
example: no
unzip: no
```
